name: File operation in github

on: push

jobs:

    files:
        runs-on: ubuntu-latest
        steps:

            -name: create a one file
              run: echo "kkdevops 123456" > devops.txt


             -name: display the content of a file
              run:  cat devops.txt

              -name: display the date
               run: date

               -name: display the files and directories 
                run: ls -lrth

                -name: display the present loaction
                 run: pwd
            